---
  extends:
    - eslint:recommended
    - plugin:react/recommended
  env:
    node: true
    mocha: true
    es2021: true
    browser: true
  globals:
    cy: readonly
  parserOptions:
    sourceType: "module"
    ecmaFeatures:
      jsx: true
  plugins:
    - only-warn
  rules:
    react/display-name: off
    react/prop-types: off
    react/react-in-jsx-scope: off
  overrides:
    - files: ["**/*.ts", "**/*.tsx"]
      parser: '@typescript-eslint/parser'
      plugins:
        - only-warn
        - '@typescript-eslint'
      extends:
        - eslint:recommended
        - plugin:react/recommended
        - plugin:@typescript-eslint/recommended
      rules:
        react/display-name: off
        react/prop-types: off
        react/react-in-jsx-scope: off
        '@typescript-eslint/no-explicit-any': off
